baseurl = "http://samuel-rosa.github.io/"  # End your URL with a `/` trailing slash.
title = "A. Samuel-Rosa"
#copyright = "&copy; 2016 Your Name"
theme = "hugo-academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
publishDir = "../samuel-rosa.github.io"

# Ignore R Markdown files
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Enable comments by entering your Disqus shortname
disqusShortname = "samuel-rosa"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "pt-br"
defaultContentLanguageInSubdir = false

[blackfriday]
  hrefTargetBlank = true

[params]
  name = "A. Samuel-Rosa"
  role = "Estagiário Pós-Doutoral"
  organization = "Universidade Federal de Santa Maria"
  organization_url = "http://site.ufsm.br/"
  gravatar = false  # Get your avatar from Gravatar.com? (true/false)
  avatar = "eu.png"  # Specify an avatar image (in `static/img/` folder) or delete value to disable avatar.
  email = "alessandrosamuelrosa@gmail.com"
  address = "Prédio 42 Sala 3314, Universidade Federal de Santa Maria, Santa Maria (RS), 97105-900, Brasil"
#  office_hours = "Monday 10:00 to 13:00 or email for appointment"
  phone = "+55 (55) 3220-8157"
  skype = "alessandrosamuel"
  telegram = ""

  # Enable Keybase in Contact section by entering your keybase.io username.
  keybase = ""

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "2006-01-02"

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = true

  # Highlight.js options
  #   highlight
  #     Enable global source code highlighting?  If false, you can
  #     override it for a particular page in that page's preamble.
  #
  #     Example: highlight = true
  #
  #   highlight_languages
  #     Add support for highlighting additional languages. Support for
  #     languages mentioned here will be included in all pages. You
  #     can also set this variable for a particular page in that
  #     page's preamble.
  #
  #     Example: highlight_languages = ["go", "lisp", "ocaml"]
  #
  #   highlight_style
  #     Choose a different CSS style for highlighting source
  #     code. Setting this option in a page's preamble has no
  #     effect.
  #
  #     Example: highlight_style = "github-gist"
  #
  #   highlight_version
  #     Choose the version of highlight.js you want. Setting this
  #     option in a page's preamble has no effect.
  #
  #     Example: highlight_version = "9.9.0"
  #
  #   For the list of supported languages, styles, and versions, see:
  #   https://cdnjs.com/libraries/highlight.js/
  #
  #   For more info on the highlighting options, see:
  #   https://gcushen.github.io/hugo-academic-demo/post/writing-markdown-latex/#highlighting-options
  highlight = true
  highlight_languages = ["r"]
  highlight_style = "github"
  # highlight_version = "9.9.0"

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = ["custom.css"]
  custom_js  = []

  # Publication types.
  #   Used to categorize publications.
  #   The index of the publication type in the list is used as its unique numerical identifier.
  #   The numeric ID is used in a publication's frontmatter to categorize it.
  #   The language can be edited below.
  #   For multi-lingual sites, copy this block to each language section at the end of this file.
  publication_types = [
    'Não categorizado',       # 0
    'Anais de evento',        # 1
    'Revista científica',     # 2
    'Trabalho em andamento',  # 3
    'Relatório técnico',      # 4
    'Livro',                  # 5
    'Capítulo de livro'       # 6
  ]

  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:alessandrosamuelrosa@gmail.com"

  [[params.social]]
    icon = "github-square"
    icon_pack = "fa"
    link = "//github.com/samuel-rosa"

  [[params.social]]
    icon = "twitter-square"
    icon_pack = "fa"
    link = "//twitter.com/ASamuelRosa"

  [[params.social]]
    icon = "researchgate-square"
    icon_pack = "ai"
    link = "//www.researchgate.net/profile/Alessandro_Samuel-Rosa"

  [[params.social]]
    icon = "google-scholar-square"
    icon_pack = "ai"
    link = "//scholar.google.co.uk/citations?user=9eloS1kAAAAJ"

  [[params.social]]
    icon = "orcid-square"
    icon_pack = "ai"
    link = "//orcid.org/0000-0003-0877-1320"

  [[params.social]]
    icon = "linkedin-square"
    icon_pack = "fa"
    link = "//www.linkedin.com/in/alessandro-samuel-rosa-b16b2753/"

  [[params.social]]
    icon = "youtube-square"
    icon_pack = "fa"
    link = "//www.youtube.com/channel/UCwIjX9SEjcIEoytAbj53tvQ"

  [[params.social]]
    icon = "slideshare"
    icon_pack = "fa"
    link = "//www.slideshare.net/alessandrosamuelrosa"

  [[params.social]]
    icon = "facebook-square"
    icon_pack = "fa"
    link = "//www.facebook.com/profile.php?id=100012343934289"


# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Início"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Publicações"
  url = "#publications_selected"
  weight = 2

[[menu.main]]
  name = "Postagens"
  url = "#posts"
  weight = 3

[[menu.main]]
  name = "Projetos"
  url = "#projects"
  weight = 4

[[menu.main]]
  name = "Ensino"
  url = "#teaching"
  weight = 5

[[menu.main]]
  name = "Contato"
  url = "#contact"
  weight = 6

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"

# Languages
#   Create a [languages.X] block for each language you want, where X is the language ID.

# Configure the English version of the website.
[languages.pt]
  languageCode = "pt-br"
