---
title: 'Building a Public Repository of Open Soil Iron Data for Brazil'
author: "Alessandro Samuel-Rosa"
event: 'BSPM 2017'
event_url: 'http://www.cena.usp.br/'
date: "2017-05-29"
location: 'Piracicaba, Brasil'
url_pdf: 'https://www.researchgate.net/publication/318404748'
url_slides: 'https://www.slideshare.net/alessandrosamuelrosa/building-a-public-repository-of-open-soil-iron-data-for-brazil'
output: html_document
---

## Resumo

We have recently stimulated the emergence of an unprecedented collaborative effort among soil scientists from all over Brazil. The goal: to build a centralized, public and free repository of standardized and georeferenced soil iron data with national coverage. Many Brazilian soil scientists have already shared datasets, some of them even before we could insert the datasets in possession of our institutions in what we called the Brazilian Soil Iron Data Repository ([Fe-BR][febr]).

[febr]: http://coral.ufsm.br/febr/

Since December 2016, Fe-BR already has some 26 thousand records from about 300 datasets, most of them from the Brazilian Soil Information System ([SISB][sisb]) maintained by Embrapa. Along this period, we have seen that soil scientists are eager to share the datasets in their possession but are very sensitive to the extra efforts needed to do so. As such, we have designed a system that relies on data manipulation tools that are well known to all -- spreadsheets. We also aimed at a suite of tools that meets the basic technological requirements of a robust but flexible data repository -- version control, persistent identification, multiple file export options, concurrent edition, reviewing tools. The free online service Google Sheets has been able to fulfil all of these requirements. With Google Sheets, datasets in Fe-BR can be reviewed and/or augmented at any time by anyone on the internet with the permission to do so. This participatory approach can potentially boost the development of a completely new type of community driven, free and open soil data repository.

[sisb]: https://www.bdsolos.cnptia.embrapa.br/consulta_publica.html

There has obviously been some difficulties, such as (1) motivating authors to provide comprehensive metadata and adhere to standards, (2) guessing spatial coordinates of non-georeferenced soil observations, (3) establishing communication between data sources, and (4) finding people willing to help in data organization and standardization. Solutions for (3) usually increase the need for more collaborators thus inflating (4). Solving (1) seems to depend upon consistent and persistent awareness raising. Fortunately the enthusiasm and sense of public responsibility of soil scientists, and availability of free online collaborative mapping services such as Google Maps, have made it easier to solve (2).

Next steps include launching a metadata catalog with search tools and improving the [febr][rfebr] package for R. Soil scientists are encouraged to use Fe-BR data to improve taxonomic systems, evaluate analytical methods, produce soil maps, identify priority areas for sampling and so on.

[rfebr]: https://github.com/samuel-rosa/febr-package

## Informações adicionais

Este trabalho foi realizado em parceria com [Ricardo Dalmolin][dalmolin], pesquisador do Programa de Pós-Graduação em Ciência do Solo ([PPGCS][ppgcs]) da Universidade Federal de Santa Maria ([UFSM][ufsm]). Participaram, também, [Paulo Gubiani][gubiani] (PPGCS/UFSM), [Stanley Oliveira][stanley] (Embrapa), [Humberto dos Santos][humberto] (Embrapa) e [Eloi Ribeiro][eloi] (ISRIC). O desenvolvimento do trabalho e sua apresentação no BSPM 2017 foram viabilizados pelo PPGCS via Programa Nacional de Pós Doutorado ([PNPD][pnpd]).

[eloi]: http://www.isric.org/user/34

[humberto]: http://lattes.cnpq.br/5351112741475859

[staley]: http://lattes.cnpq.br/5321244029568287

[gubiani]: http://lattes.cnpq.br/7251203817503318

[dalmolin]: http://lattes.cnpq.br/3735884911693854

[ufsm]: http://site.ufsm.br/

[ppgcs]: http://w3.ufsm.br/ppgcs/index.php

[pnpd]: http://www.capes.gov.br/bolsas/bolsas-no-pais/pnpd-capes
