---
title: 'Uma aliança global pelo solo para alcançar o desenvolvimento sustentável'
author: "Alessandro Samuel-Rosa"
event: 'Expo Santa Helena 2018'
event_url: 'https://www.facebook.com/exposantahelena/'
date: "2018-05-27"
location: 'Santa Helena, Brasil'
url_pdf: ''
url_slides: 'https://www.slideshare.net/alessandrosamuelrosa/uma-aliana-global-pelo-solo-para-alcanar-o-desenvolvimento-sustentvel'
output: html_document
---

## Resumo

O solo é um recurso natural muito lentamente renovável que ocupa posição central nos agroecossistemas. Mesmo 
assim, o solo continua sendo degradado pela má gestão e pelas mudanças inconsequentes do uso da terra. Para 
promover uma mudança real na maneira como usamos esse precioso recurso, instituições de vários países, 
coordenadas pela Organização das Nações Unidas para a Alimentação e a Agricultura (FAO), juntaram esforços para
constituir uma Aliança Global pelo Solo. A Aliança possui cinco pilares de ação: (1) gestão do solo, (2) 
sensibilização, (3) pesquisa, (4) informação e dados, e (5) harmonização. Nessa palestra, nós vamos explicar 
cada um dos cinco pilares de ação. Também vamos mostrar como as instituições de ensino, pesquisa e extensão 
brasileiras vem atuando para implementar as ações da Aliança. Algumas das maneiras como a comunidade de Santa 
Helena e região podem contribuir para esse esforço global (e também se beneficiar dele) serão apresentadas. O 
público é encorajado a participar fazendo perguntas e comentários, sobretudo para que a UTFPR-SH possa melhor 
direcionar suas ações de ensino, pesquisa e extensão para ajudar a região a alcançar o desenvolvimento 
sustentável.
