---
title: 'Bringing together Brazilian soil scientists to share soil data'
author: "Alessandro Samuel-Rosa"
event: '21st World Congress of Soil Science'
event_url: 'https://www.21wcss.org/'
date: "2018-08-14"
location: 'Rio de Janeiro, Brasil'
url_pdf: 'https://www.researchgate.net/publication/327162497'
url_slides: 'https://www.slideshare.net/alessandrosamuelrosa/bringing-together-brazilian-soil-scientists-to-share-soil-data'
output: html_document
---

## Resumo

Soil science has produced a great deal of data. Most of the information is published as a single paper, and the primary data is unavailable to other researchers. As data underutilization is a waste of resources and refrains the advancement of knowledge, many isolated soil data rescue and sharing efforts have emerged in the scientific community. Lately, soil scientists have increased their concerns with data discoverability and reusability, and reproducible research. To address these issues, Brazilian soil scientists have recently created a data repository using community-built standards and following open data policies. The Free Brazilian Repository for Open Soil Data -- ___febr___, www.ufsm.br/febr – is a centralized repository targeted at storing open soil data and serving it in a standardized and harmonized format. The repository infrastructure was built using open source and/or free (of cost) software, and was primarily designed for the individual management of datasets. A dataset-driven structure helps datasets authors to be properly acknowledged. Moreover, it gives the flexibility to accommodate many types of data of any soil variable. This is accomplished by storing each dataset using a collection of spreadsheets accessible through an online application. Spreadsheets are familiar to any soil scientist, the reason why it is easier to enter, manipulate and visualize soil data in febr. They also facilitate the participation of soil survey experts in the recovery and quality assessment of legacy data. Soil scientists can help in the definition of standards and data management choices through a public discussion forum, febr-forum@googlegroups.com. A comprehensive documentation is available to guide febr maintainers and data contributors. A detailed catalog gives access to the 14 477 soil observations -- 42% of them from south and southeastern Brazil -- from 232 datasets contained in ___febr___. Global and dataset-specific visualization and search tools and multiple download facilities are available. The latter includes standard file formats and connections with R and QGIS through the ___febr___ package. Various products can be derived from data in ___febr___: specialized databases, pedotransfer functions, fertilizer recommendation guides, classification systems, and detailed soil maps. By sharing data through a centralized soil data storing and sharing facility, soil scientists from different fields have the opportunity to increase collaboration and the much needed soil knowledge.

## Informações adicionais

Este trabalho foi realizado em parceria com [Ricardo Simão Diniz Dalmolin][dalmolin], [Paulo Ivonir Gubiani][gubiani], [Stanley Robson de Medeiros Oliveira][stanley], [Wenceslau Geraldes Teixeira][wenceslau], [João Herbert Moreira Viana][herbert], e outros 48 pesquisadores. O desenvolvimento do trabalho e sua apresentação foram viabilizados pelo Programa de Pós-Graduação em Ciência do Solo ([PPGCS][ppgcs]) da Universidade Federal de Santa Maria ([UFSM][ufsm]), via Programa Nacional de Pós Doutorado ([PNPD][pnpd]), e pela Coordenação de Agronomia da Universidade Tecnológica Federal do Paraná -- câmpus Santa Helena ([UTFPR-SH][utfpr]), via Fundação Araucária de Apoio ao Desenvolvimento Científico e Tecnológico do Estado do Paraná ([FA][fa]).

[gubiani]: http://lattes.cnpq.br/7251203817503318
[dalmolin]: http://lattes.cnpq.br/3735884911693854
[stanley]: http://lattes.cnpq.br/5321244029568287
[wenceslau]: http://lattes.cnpq.br/4136381865367906
[herbert]: http://lattes.cnpq.br/5963012432691034

[ufsm]: http://site.ufsm.br/
[ppgcs]: http://w3.ufsm.br/ppgcs/index.php
[pnpd]: http://www.capes.gov.br/bolsas/bolsas-no-pais/pnpd-capes
[utfpr]: http://portal.utfpr.edu.br/campus/santahelena
[fa]: http://www.fappr.pr.gov.br/
