---
title: 'The Free Brazilian Repository for Open Soil Data'
author: "Alessandro Samuel-Rosa"
event: 'Latin America and the Caribbean Scientific Data Management Workshop'
event_url: 'http://lacworkshop.icsu-wds.org/'
date: "2018-04-17"
location: 'Rio de Janeiro, Brasil'
url_pdf: 'https://www.researchgate.net/publication/325553121'
url_slides: 'https://www.slideshare.net/alessandrosamuelrosa/the-free-brazilian-repository-for-open-soil-data-febr'
output: html_document
---

## Resumo

Brazilian soil science has produced a great deal of data. Most of the information is published as a single 
paper, and the primary data is unavailable to other researchers. Lately, soil scientists have increased their 
concerns with data discoverability and reusability, and reproducible research. To address this issue, Brazilian
soil scientists have recently created a data repository using community-built standards and following open data
policies. The Free Brazilian Repository for Open Soil Data – febr, www.ufsm.br/febr – is a centralized 
repository targeted at storing open soil data and serving it in a standardized and harmonized format. The 
repository infrastructure was built using open source and/or free (of cost) software, and was primarily 
designed for the individual management of datasets. This is accomplished by storing each dataset using a 
collection of Google spreadsheets accessible online. Spreadsheets are familiar to any soil scientist, the 
reason why it is easier to enter, manipulate and visualize soil data in febr. Soil scientists can help in the
definition of standards and data management choices through a public discussion forum, 
febr-forum@googlegroups.com. A comprehensive documentation is available to guide febr maintainers and data 
contributors. A detailed catalog gives access to the 14 477 soil observations from 232 datasets contained in 
febr. Global and dataset-specific visualization and search tools and multiple download facilities are 
available. The latter includes standard file formats and connections with R and QGIS through the febr package. 
Various products can be derived from data in febr: specialized databases, pedotransfer functions, fertilizer 
recommendation guides, classification systems, and detailed soil maps.

## Informações adicionais

Este trabalho foi realizado em parceria com [Ricardo Dalmolin][dalmolin] e [Paulo Gubiani][gubiani], 
pesquisadores do Programa de Pós-Graduação em Ciência do Solo ([PPGCS][ppgcs]) da Universidade Federal de Santa
Maria ([UFSM][ufsm]). O desenvolvimento do trabalho e sua apresentação no *workshop* foram viabilizados pelo 
PPGCS via Programa Nacional de Pós Doutorado ([PNPD][pnpd]) e pela [Fundação Agrisus][agrisus].

[gubiani]: http://lattes.cnpq.br/7251203817503318

[dalmolin]: http://lattes.cnpq.br/3735884911693854

[ufsm]: http://site.ufsm.br/

[ppgcs]: http://w3.ufsm.br/ppgcs/index.php

[pnpd]: http://www.capes.gov.br/bolsas/bolsas-no-pais/pnpd-capes

[agrisus]: http://agrisus.org.br/menu_br.asp
