---
title: Programas de Computador
summary: Implementação algorítmica de métodos e técnicas de uso em pedologia quantitativa
author: Alessandro Samuel-Rosa
date: "`r Sys.Date()`"
slug: programas-de-computador
tags: ["R"]
---

Eu já desenvolvi diversos programas de computados ao longo de minha curta carreira científica. Parte 
considerável deles está voltada à escrita científica, como 1) os *'arquivos de estilo `jstyle` para formatação 
automática de referências bibliográficas usando JabRef e LibreOffice'* 
([link](https://github.com/samuel-rosa/RefBib)), 2) o *'pacote \LaTeX `pedometrianews` para formatação da 
Newsletter da Comissão de Pedometria da Sociedade Brasileira de Ciência do Solo'* 
([link](https://github.com/samuel-rosa/pedometrianews)) e 3) a *'classe \LaTeX `UFRuralRJ` para formatação de
documentos acadêmicos da Universidade Federal Rural do Rio de Janeiro'* 
([link](https://github.com/samuel-rosa/UFRuralRJ)).

No momento, além do pacote `spsann` para o `R`, desenvolvo um segundo pacote com aplicação na pedologia 
quantitativa. Trata-se do pacote `pedometrics`, que contém ferramentas e técnicas diversas para pedologia
quantitativa, um produto do projeto

* ***Implementação algorítmica de métodos e técnicas de uso em pedologia quantitativa***

A última versão do pacote `pedometrics` pode ser descarregada gratuitamente de 
https://cran.r-project.org/web/packages/pedometrics/.
