---
title: Amostragem Espacial
summary: "Otimização espacial de configurações amostrais utilizando recozimento simulado."
author: Alessandro Samuel-Rosa
date: '2017-09-18'
slug: amostragem-espacial
categories: []
tags:
  - amostragem
  - otimização
  - R
---

O uso de estratégias amostrais robustas é fundamental para a estimativa de parâmetros e predição do 
comportamento espacial de recursos naturais com mínima incerteza. Dentro dessa temática, atualmente, 
desenvolvo o projeto

* ***Otimização espacial de configurações amostrais utilizando recozimento simulado***

O desenvolvimento desse projeto teve início durante meu doutoramento na UFRRJ. Portanto, trata-se de uma
parceria com Lúcia Anjos (UFRRJ), Gustavo Vasques (Embrapa Solos), Gerard Heuvelink (ISRIC World Soil
Information, Holanda) e Dick Brus (Wageningen University and Research Centre, Holanda). Algumas publicações
importantes resultantes desse projeto são:

1. Optimization of sample configurations for spatial trend estimation
   ([link](http://dx.doi.org/10.13140/RG.2.1.2198.5769))
2. Optimization of sample configurations for variogram estimation
   ([link](http://dx.doi.org/10.13140/RG.2.1.1412.1440))
3. spsann -- optimization of sample patterns using spatial simulated annealing
   ([link](http://meetingorganizer.copernicus.org/EGU2015/EGU2015-7780.pdf))

Em termos práticos, a contribuição mais importante desse projeto é o pacote `spsann` para o `R`, que contém 
ferramentas para otimização espacial de configurações amostrais usando recozimento simulado. A última versão
publicada do pacote pode ser descarregada gratuitamente de https://cran.r-project.org/web/packages/spsann/.
