---
title: 'Feliz Dia Mundial do Solo'
summary: 'Atividades em alusão do Dia Mundial do Solo 2017 na UFSantaMaria'
author: Alessandro Samuel-Rosa
date: '2017-12-04'
slug: dia-mundial-solo-2017
tags:
  - ensino
  - pedometria
  - ufsm
  - solo
output:
  blogdown::html_page:
    toc: true
---

O Programa de Pós-Graduação Ciência do Solo da Universidade Federal de Santa Maria (UFSantaMaria) convida a
comunidade em geral para participar das atividades em alusão ao Dia Mundial do Solo.

Na quarta-feira, dia 06/12, das 13:30 às 17:30, será realizado o **Seminário Dia Mundial do Solo UFSM 2017**, 
no Auditório Flávio Miguel Schneider, Centro de Ciências Rurais, Prédio 42. Neste seminário, os 
pós-doutorandos(as) do PPG Ciência do Solo apresentarão um panorama das pesquisas realizadas no último ano,
apontando para os principais desenvolvimentos em suas áreas e perspectivas futuras. Veja abaixo os principais
tópicos que serão apresentados e discutidos no evento.

Na quinta-feira, dia 07/12, das 08:00 às 12:00, será realizada a **Oficina de Dados Abertos do Solo**, na Sala 
Enio Tonini, Centro de Ciências Rurais, Prédio 43. A Oficina é baseada na experiência acumulada durante a 
construção e manutenção do Repositório Brasileiro Livre para Dados Abertos do Solo (febr, www.ufsm.br/febr), 
repositório este desenvolvido pela equipe coordenada pelos pesquisadores do PPG Ciência do Solo Dr. Alessandro 
Samuel-Rosa, Dr. Ricardo Simão Diniz Dalmolin e Dr. Paulo Ivonir Gubiani. Os participantes devem levar seus 
computadores pessoais para as atividades práticas e receberão certificado de participação.

Maiores informações em <www.ufsm.br/ppgcs>.
