---
title: 'Oficina de mapeamento digital do solo para agricultura de precisão'
author: Alessandro Samuel-Rosa
date: '2019-01-25'
slug: 2019-mds-para-agricultura-de-precisao
tags:
  - ensino
  - unicamp
  - feagri
output:
  blogdown::html_page:
    toc: true
---

# Descrição geral

## Identificação

__Instituição__: Universidade Estadual de Campinas<br>
__Unidade__: Faculdade de Engenharia Agrícola<br>
__Carga horária__: 12 horas (AT = 3; AP = 9)<br>
__Nível__: Pós-graduação<br>
__Instrutor__: Alessandro Samuel-Rosa<br>
__Material__: https://github.com/samuel-rosa/feagri-dsm-workshop

## Calendário de aulas

__Data__: 25 e 26 de janeiro de 2019<br>
__Horário__: 09:00-12:30 (25/01), 14:00-19:00 (25/01), 14:30-18:00 (26/01)<br>
__Local__: Laboratório de Geoprocessamento

## Objetivos

Os objetivos da oficina são os seguintes:

* Revisar os fundamentos da formação do solo e os fatores ambientais que interferem sobre ela em áreas de 
  produção agrícola.
* Conhecer as bases do mapeamento digital do solo.
* Compreender como covariáveis ambientais podem ser usadas, em modelos de predição espacial do solo, para 
  representar os fatores ambientais que interferem sobre a formação do solo em áreas de produção agrícola.
* Conhecer técnicas avançadas de aprendizado de máquina que podem ser utilizadas para a predição espacial do 
  solo na agricultura de precisão.
* Explorar a validação cruzada como técnica de avaliação da qualidade das predições espaciais do solo na 
  agricultura de precisão.

## Conteúdo

1. Gênese e distribuição espacial do solo
   1.1 Fatores de formação do solo: o modelo clorpt
       - Derivation of state factor equations of soils and ecosystems ([Jenny, 1961][jenny])
   1.2 Processos gerais de formação do solo: adições, perdas, translocações e transformações
       - Outline of a generalized theory of soil genesis ([Simonson, 1959][simonson])
   1.3 Autocorrelação espacial: semivariograma
       - How geostatistics can help you ([Oliver e Webster, 1991][oliver])
2. Covariáveis ambientais
   2.1 Indicadores dos fatores de formação do solo
       - Do more detailed environmental covariates deliver more accurate soil maps? ([Samuel-Rosa et al., 2015][samuelrosa])
   2.2 Clima e material de origem: mapas meteorológico e geológico
   2.3 Relevo: modelo digital de elevação e atributos derivados
   2.4 Organismos:
       a. Vegetação: imagens de orbitais e suborbitais
       b. Ação antrópica: mapas de manejo do solo
   2.5 Solo: sensores proximais mapas de propriedades do solo
3. Aprendizado de máquina
   3.1 Correlação ambiental
       - Soil attribute prediction using terrain analysis ([Moore et al., 1993][moore])
   3.2 Métodos de aprendizado de máquina:
       a. Regressão linear múltipla
       b. Árvore de regressão
          - Induction of decision trees ([Quinlan, 1986][quinlan])
       c. Floresta aleatória
          - Random forests ([Breiman, 2001][breiman])
4. Modelo linear misto de variação espacial
   4.1 Efeitos fixos e aleatórios: o modelo scorpan
       - On digital soil mapping ([McBratney et al., 2003][mcbratney])
   4.2 Calibração, predição e validação
       - On spatial prediction of soil properties in the presence of a spatial trend: the empirical best linear
         unbiased predictor (E-BLUP) with REML ([Lark et al., 2006][lark])
       - Sampling for validation of digital soil maps ([Brus et al., 2011][brus])
5. Atividades práticas

[jenny]: https://doi.org/10.2136/sssaj1961.03615995002500050023x
[simonson]: http://www.evsc.virginia.edu/~alm7d/soils/handouts/simonson.pdf
[oliver]: https://doi.org/10.1111/j.1475-2743.1991.tb00876.x
[samuelrosa]: https://doi.org/10.1016/j.geoderma.2014.12.017
[moore]: https://doi.org/10.2136/sssaj1993.03615995005700020026x
[quinlan]: https://link.springer.com/article/10.1007%2FBF00116251
[breiman]: https://link.springer.com/article/10.1023%2FA%3A1010933404324
[mcbratney]: https://linkinghub.elsevier.com/retrieve/pii/S0016706103002234
[lark]: https://doi.org/10.1111/j.1365-2389.2005.00768.x
[brus]: https://doi.org/10.1111/j.1365-2389.2011.01364.x
